version: "3"
services:
  expense-tracker-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=discord
      - POSTGRES_PASSWORD=discord
    ports:
      - "5433:5432"
    volumes:
      - expense-tracker-db:/var/lib/postgresql/data
volumes:
  expense-tracker-db:
    driver: local
